version: '3.9'

services:
  pytorch-jupyter:
    image: cyberhead1998/pytorch-jupyter:latest  # Replace with your Docker Hub image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace  # Mount a local folder to persist your work
