version: '3.9'

services:
  pytorch-jupyter:
    image: yourusername/pytorch-jupyter:latest  # Replace with your Docker Hub image
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia  # Use NVIDIA runtime for GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/workspace  # Mount a local folder to persist your work
